import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

/**
 * This file is autogenerated by the dApp builder.
 * You should not edit it manually.
 */

const deployedContracts = {
  // Contract deployments will be added here
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
